name: 'executable-wrapper'
description: 'GitHub action that wraps executables and returns the stdout, stderr and exit code.'
author: 'Maddog2050'
inputs:
  run_command:
    description: 'The executable along with any parameters that need sto be run.'
    required: true
  encode_stdout:
    description: 'If true URI encodes the stdout (default false).'
    required: false
    default: 'false'
  encode_stderr:
    description: 'If true URI encodes the stderr (default false).'
    required: false
    default: 'false'
outputs:
  stdout:
    description: 'The stdout output from the executable.'
  stderr:
    description: 'The stderr output from the executable.'
  exitcode:
    description: 'The exit code from the executable.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: gift
  color: purple
